# This is a basic workflow to help you get started with Actions

name: generateLogPage

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # html整形のためのおまじないのためのおまじない
    strategy:
      matrix:
        node-version: [15.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      # html整形のためのおまじない
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      
      # ログリストを生成
      - name: Run a python script
        run: |
          python3 .github/workflows/generator.py > logViewer.html

      # 生成されたhtmlを整形
      - name: Run Prettier
        run: |
          npx prettier --write logViewer.html

      - name: push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"
          git push



