# This is a basic workflow to help you get started with Actions

name: generateLogPage

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      # ログリストを生成
      - name: Run a python script
        run: |
          python3 .github/workflows/generator.py > logViewer.html

      # Job for Minify-JS
      - name: Minify-JS Action
        uses: jossydevers/minify-js@v1.0.1
        with:
          directory: 'logViewer.html' # (OPTIONAL)
          output: './'

      # minifyの出力は.min.htmlなのでリネーム
      - name: rename logViewer
        run: |
          rm logViewer.html
          mv logViewer.min.html logViewer.html
          cat logViewer.html

      # 成果物をプッシュ
      - name: push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"
          git push



